name: Build & upload to Firebase App Distribution
on:
  push:
    branches:
      - master

jobs:
 build_ios:
    name: Build Flutter (iOS)
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_SCHEME: ${{ 'flutter_ci' }}
      XC_CONFIGURATION: ${{ 'Automation' }}
      XC_WORKSPACE: ${{ 'flutter_ci.xcworkspace' }}
      XC_ARCHIVE_PATH: ${{ './flutter_ci.xcarchive' }}
      XC_EXPORT_PATH: ${{ './artifacts/' }}
      XC_EXPORT_OPTIONS_FILE_PATH: ${{ './ExportOptions.plist' }}
      ENCRYPTED_CERTS_FILE_PATH: ${{ './certs.p12.gpg' }}
      DECRYPTED_CERTS_FILE_PATH: ${{ './certs.p12' }}
      ENCRYPTED_PROVISION_FILE_PATH: ${{ './provisioning.tar.gz.gpg' }}
      DECRYPTED_PROVISION_FILE_PATH: ${{ './provisioning.tar.gz' }}
      CERTS_ENCRYPTION_PWD: ${{ secrets.CERTS_ENCRYPTION_PWD }}
      PROVISION_ENCRYPTION_PWD: ${{ secrets.PROVISION_ENCRYPTION_PWD }}
      CERTS_EXPORT_PWD: ${{ secrets.CERTS_EXPORT_PWD }}
      KEYCHAIN: ${{ 'test.keychain' }}
    steps:
      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: Configure Keychain
        run: |
          security create-keychain -p "" "$KEYCHAIN"
          security list-keychains -s "$KEYCHAIN"
          security default-keychain -s "$KEYCHAIN"
          security unlock-keychain -p "" "$KEYCHAIN"
          security set-keychain-settings
          security list-keychains
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - name: Upload ipa
        uses: actions/upload-artifact@master
        with:
          name: ios-build
          path: build/ios/iphoneos
 beta_ios:
    name: Upload iOS Beta to Firebase App Distribution
    needs: [build_ios]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.1.1
        with:
          channel: 'dev'
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ios-build
#      - name: Upload IPA
#        uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
#        with:
#          appId: ${{secrets.FIREBASE_IOS_APPID}}
#          token: ${{secrets.FIREBASE_TOKEN}}
#          groups: testers
#          file: Runner.ipa
    - name: Build
#        env:
#          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
#          MATCH_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
#        run: |
#          cd ios
#          fastlane build
        - name: Use Node.js 8.x
          uses: actions/setup-node@v1
          with:
            node-version: 8.x
        - name: Install Firebase
          run: yarn install
        - name: Upload ipa
          run: yarn run firebase appdistribution:distribute ios/build/Runner.ipa --app "${{ secrets.FIREBASE_IOS_APPID }}" --token "${{ secrets.FIREBASE_TOKEN }}"

